In [25]:
import pandas as pd
import numpy as np

In [26]:
data=pd.read_csv(r'C:/Users/Acer/Downloads/car_data.csv')

In [27]:
data

User ID  Gender  Age  AnnualSalary  Purchased
0        385    Male   35         20000          0
1        681    Male   40         43500          0
2        353    Male   49         74000          0
3        895    Male   40        107500          1
4        661    Male   25         79000          0
..       ...     ...  ...           ...        ...
995      863    Male   38         59000          0
996      800  Female   47         23500          0
997      407  Female   28        138500          1
998      299  Female   48        134000          1
999      687  Female   44         73500          0

[1000 rows x 5 columns]

In [28]:
data.isna().any()

User ID         False
Gender          False
Age             False
AnnualSalary    False
Purchased       False
dtype: bool

In [29]:
X_data=data.iloc[:, 1:-1]

In [30]:
# from sklearn.preprocessing import StandardScaler
# scaler= StandardScaler()
# scaler.fit_transform(X)

In [31]:
X=pd.get_dummies(X_data).values

In [32]:
Y=data['Purchased'].values

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X, Y, test_size=0.2, random_state=0)

In [36]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [37]:
classifier.fit(X_train, Y_train)

RandomForestClassifier()

In [38]:
prediction=classifier.predict(X_test)

In [43]:
prediction

array([1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0], dtype=int64)

In [46]:
probability=classifier.predict_proba(X_test)[0]

In [48]:
probability

array([0.08, 0.92])

In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score
score1=confusion_matrix(Y_test, prediction)
score2=accuracy_score(Y_test, prediction)

In [50]:
score1

array([[113,   8],
       [  8,  71]], dtype=int64)

In [51]:
score2

0.92