In [1]:
import pandas as pd
import numpy as np
import sklearn

In [2]:
data=pd.read_csv(r'C:/Users/Acer/Downloads/rent.csv')

In [3]:
data

Posted On  BHK   Rent  Size            Floor    Area Type  \
0     5/18/2022    2  10000  1100  Ground out of 2   Super Area   
1     5/13/2022    2  20000   800       1 out of 3   Super Area   
2     5/16/2022    2  17000  1000       1 out of 3   Super Area   
3      7/4/2022    2  10000   800       1 out of 2   Super Area   
4      5/9/2022    2   7500   850       1 out of 2  Carpet Area   
...         ...  ...    ...   ...              ...          ...   
4741  5/18/2022    2  15000  1000       3 out of 5  Carpet Area   
4742  5/15/2022    3  29000  2000       1 out of 4   Super Area   
4743  7/10/2022    3  35000  1750       3 out of 5  Carpet Area   
4744   7/6/2022    3  45000  1500     23 out of 34  Carpet Area   
4745   5/4/2022    2  15000  1000       4 out of 5  Carpet Area   

                 Area Locality       City Furnishing Status  Tenant Preferred  \
0                       Bandel    Kolkata       Unfurnished  Bachelors/Family   
1     Phool Bagan, Kankurgachi    Kolkata    Semi-Furnished  Bachelors/Family   
2      Salt Lake City Sector 2    Kolkata    Semi-Furnished  Bachelors/Family   
3                  Dumdum Park    Kolkata       Unfurnished  Bachelors/Family   
4                South Dum Dum    Kolkata       Unfurnished         Bachelors   
...                        ...        ...               ...               ...   
4741              Bandam Kommu  Hyderabad    Semi-Furnished  Bachelors/Family   
4742      Manikonda, Hyderabad  Hyderabad    Semi-Furnished  Bachelors/Family   
4743      Himayath Nagar, NH 7  Hyderabad    Semi-Furnished  Bachelors/Family   
4744                Gachibowli  Hyderabad    Semi-Furnished            Family   
4745           Suchitra Circle  Hyderabad       Unfurnished         Bachelors   

      Bathroom Point of Contact  
0            2    Contact Owner  
1            1    Contact Owner  
2            1    Contact Owner  
3            1    Contact Owner  
4            1    Contact Owner  
...        ...              ...  
4741         2    Contact Owner  
4742         3    Contact Owner  
4743         3    Contact Agent  
4744         2    Contact Agent  
4745         2    Contact Owner  

[4746 rows x 12 columns]

In [4]:
date=pd.to_datetime(data['Posted On']).dt.month_name()

In [5]:
data.dtypes

Posted On            object
BHK                   int64
Rent                  int64
Size                  int64
Floor                object
Area Type            object
Area Locality        object
City                 object
Furnishing Status    object
Tenant Preferred     object
Bathroom              int64
Point of Contact     object
dtype: object

In [6]:
x_data=data.drop(['Rent', 'Posted On'], axis=1)

In [7]:
X=pd.get_dummies(x_data).values

In [8]:
X

array([[   2, 1100,    2, ...,    0,    0,    1],
       [   2,  800,    1, ...,    0,    0,    1],
       [   2, 1000,    1, ...,    0,    0,    1],
       ...,
       [   3, 1750,    3, ...,    1,    0,    0],
       [   3, 1500,    2, ...,    1,    0,    0],
       [   2, 1000,    2, ...,    0,    0,    1]], dtype=int64)

In [9]:
Y=data['Rent'].values

In [10]:
from sklearn.model_selection import train_test_split 
X_train, X_test, Y_train, Y_test=train_test_split(X, Y, test_size=0.05, random_state=0)

In [11]:
from sklearn.ensemble import RandomForestRegressor

In [12]:
usaq=RandomForestRegressor()

In [13]:
usaq.fit(X_train, Y_train)

RandomForestRegressor()

In [14]:
prediction=usaq.predict(X_test)

In [15]:
prediction[:5]

array([24699.99, 34419.99, 13540.  , 10880.5 , 39365.  ])

In [16]:
Y_test[:5]

array([50000, 15000, 12000, 13000, 48000], dtype=int64)

In [17]:
from sklearn.metrics import r2_score, mean_squared_error

In [18]:
score1=r2_score(Y_test, prediction)

In [19]:
score2=np.sqrt(mean_squared_error(Y_test, prediction))

In [20]:
score1

0.8655440415118697

In [21]:
score2

14770.062332428524

In [22]:
data['Rent'].min()

1200

In [23]:
data['Rent'].max()

3500000

In [24]:
from sklearn.tree import DecisionTreeRegressor

In [25]:
usaq=DecisionTreeRegressor()

In [26]:
usaq.fit(X_train, Y_train)

DecisionTreeRegressor()

In [27]:
prediction=usaq.predict(X_test)

In [28]:
prediction[:5]

array([25000., 39000., 12500., 12000., 35000.])

In [29]:
Y_test[:5]

array([50000, 15000, 12000, 13000, 48000], dtype=int64)

In [30]:
from sklearn.metrics import r2_score, mean_squared_error

In [31]:
score1=r2_score(Y_test, prediction)

In [32]:
score1

0.7674603523591554